#!/usr/bin/groovy

pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    stages {

        stage("Build") {
            steps { buildApp() }
		}

		stage("Test - Unit tests") {
            steps { runUnittests() }
		}

        stage("Deploy - Dev") {
            steps { deploy('dev') }
		}

		stage("Test - UAT Dev") {
            steps { runUAT(8888) }
		}

        stage("Deploy - Stage") {
            steps { deploy('stage') }
		}

		stage("Test - UAT Stage") {
            steps { runUAT(88) }
		}

        stage("Approve") {
            steps { approve() }
		}

        stage("Deploy - Prod") {
            steps { deploy('prod') }
		}

		stage("Test - UAT Prod") {
            steps { runUAT(80) }
		}

	}
}


// steps
def buildApp() {
	dir ('section_4/code/cd_pipeline' ) {
		def appImage = docker.build("hands-on-jenkins/myapp:${BUILD_NUMBER}")
	}
}

def deploy(environment) {

	def containerName = ''
	def port = ''

	if ("${environment}" == 'dev') {
		containerName = "app_dev"
		port = "8888"
	} 
	else if ("${environment}" == 'stage') {
		containerName = "app_stage"
		port = "88"
	}
	else if ("${environment}" == 'prod') {
		containerName = "app_prod"
		port = "80"
	}
	else {
		println "Environment not valid"
		System.exit(0)
	}

	sh "docker ps -f name=${containerName} -q | xargs --no-run-if-empty docker container stop"
	sh "docker container ls -a -fname=${containerName} -q | xargs -r docker container rm"
	sh "docker run -d -p ${port}:5000 --name ${containerName} hands-on-jenkins/myapp:${BUILD_NUMBER}"

}


def approve() {

	timeout(time:1, unit:'DAYS') {
		input('Do you want to deploy to production?')
	}

}


def runUAT(port) {

	sh "section_4/code/cd_pipeline/tests/runUAT.sh ${port}"

}


def runUnittests() {

	sh "export PYTHONPATH=${PYTHONPATH}:${pwd}/section_4/code/cd_pipeline/; python section_4/code/cd_pipeline/tests/test_flask_app.py"

}
